// Code generated by MockGen. DO NOT EDIT.
// Source: linkedpage.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "ratri/src/domain/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLinkedPageRepository is a mock of LinkedPageRepository interface.
type MockLinkedPageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkedPageRepositoryMockRecorder
}

// MockLinkedPageRepositoryMockRecorder is the mock recorder for MockLinkedPageRepository.
type MockLinkedPageRepositoryMockRecorder struct {
	mock *MockLinkedPageRepository
}

// NewMockLinkedPageRepository creates a new mock instance.
func NewMockLinkedPageRepository(ctrl *gomock.Controller) *MockLinkedPageRepository {
	mock := &MockLinkedPageRepository{ctrl: ctrl}
	mock.recorder = &MockLinkedPageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkedPageRepository) EXPECT() *MockLinkedPageRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLinkedPageRepository) Get(linkedPageId int) (model.LinkedPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", linkedPageId)
	ret0, _ := ret[0].(model.LinkedPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLinkedPageRepositoryMockRecorder) Get(linkedPageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLinkedPageRepository)(nil).Get), linkedPageId)
}

// GetBySearchPageIds mocks base method.
func (m *MockLinkedPageRepository) GetBySearchPageIds(pageId []int, taskId, top int) (*[]model.SearchPageWithLinkedPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySearchPageIds", pageId, taskId, top)
	ret0, _ := ret[0].(*[]model.SearchPageWithLinkedPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySearchPageIds indicates an expected call of GetBySearchPageIds.
func (mr *MockLinkedPageRepositoryMockRecorder) GetBySearchPageIds(pageId, taskId, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySearchPageIds", reflect.TypeOf((*MockLinkedPageRepository)(nil).GetBySearchPageIds), pageId, taskId, top)
}

// GetRatioBySearchPageIds mocks base method.
func (m *MockLinkedPageRepository) GetRatioBySearchPageIds(pageId []int, taskId int) (*[]model.SearchPageWithLinkedPageRatio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRatioBySearchPageIds", pageId, taskId)
	ret0, _ := ret[0].(*[]model.SearchPageWithLinkedPageRatio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRatioBySearchPageIds indicates an expected call of GetRatioBySearchPageIds.
func (mr *MockLinkedPageRepositoryMockRecorder) GetRatioBySearchPageIds(pageId, taskId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatioBySearchPageIds", reflect.TypeOf((*MockLinkedPageRepository)(nil).GetRatioBySearchPageIds), pageId, taskId)
}

// List mocks base method.
func (m *MockLinkedPageRepository) List(offset, limit int) (*[]model.LinkedPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", offset, limit)
	ret0, _ := ret[0].(*[]model.LinkedPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLinkedPageRepositoryMockRecorder) List(offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLinkedPageRepository)(nil).List), offset, limit)
}

// Select mocks base method.
func (m *MockLinkedPageRepository) Select(linkedPageIds []int) (*[]model.LinkedPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", linkedPageIds)
	ret0, _ := ret[0].(*[]model.LinkedPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockLinkedPageRepositoryMockRecorder) Select(linkedPageIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockLinkedPageRepository)(nil).Select), linkedPageIds)
}
