// Code generated by MockGen. DO NOT EDIT.
// Source: task.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	model "ratri/src/domain/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTaskUsecase is a mock of TaskUsecase interface.
type MockTaskUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockTaskUsecaseMockRecorder
}

// MockTaskUsecaseMockRecorder is the mock recorder for MockTaskUsecase.
type MockTaskUsecaseMockRecorder struct {
	mock *MockTaskUsecase
}

// NewMockTaskUsecase creates a new mock instance.
func NewMockTaskUsecase(ctrl *gomock.Controller) *MockTaskUsecase {
	mock := &MockTaskUsecase{ctrl: ctrl}
	mock.recorder = &MockTaskUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskUsecase) EXPECT() *MockTaskUsecaseMockRecorder {
	return m.recorder
}

// CreateTaskAnswer mocks base method.
func (m *MockTaskUsecase) CreateTaskAnswer(answer *model.Answer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskAnswer", answer)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTaskAnswer indicates an expected call of CreateTaskAnswer.
func (mr *MockTaskUsecaseMockRecorder) CreateTaskAnswer(answer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskAnswer", reflect.TypeOf((*MockTaskUsecase)(nil).CreateTaskAnswer), answer)
}

// FetchTaskInfo mocks base method.
func (m *MockTaskUsecase) FetchTaskInfo(taskId int) (model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTaskInfo", taskId)
	ret0, _ := ret[0].(model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTaskInfo indicates an expected call of FetchTaskInfo.
func (mr *MockTaskUsecaseMockRecorder) FetchTaskInfo(taskId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTaskInfo", reflect.TypeOf((*MockTaskUsecase)(nil).FetchTaskInfo), taskId)
}
