// Code generated by MockGen. DO NOT EDIT.
// Source: log.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "ratri/internal/domain/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLogRepository is a mock of LogRepository interface.
type MockLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLogRepositoryMockRecorder
}

// MockLogRepositoryMockRecorder is the mock recorder for MockLogRepository.
type MockLogRepositoryMockRecorder struct {
	mock *MockLogRepository
}

// NewMockLogRepository creates a new mock instance.
func NewMockLogRepository(ctrl *gomock.Controller) *MockLogRepository {
	mock := &MockLogRepository{ctrl: ctrl}
	mock.recorder = &MockLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogRepository) EXPECT() *MockLogRepositoryMockRecorder {
	return m.recorder
}

// CumulatePageViewingTime mocks base method.
func (m *MockLogRepository) CumulatePageViewingTime(arg0 *model.PageViewingLogParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CumulatePageViewingTime", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CumulatePageViewingTime indicates an expected call of CumulatePageViewingTime.
func (mr *MockLogRepositoryMockRecorder) CumulatePageViewingTime(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CumulatePageViewingTime", reflect.TypeOf((*MockLogRepository)(nil).CumulatePageViewingTime), arg0)
}

// CumulateSerpViewingTime mocks base method.
func (m *MockLogRepository) CumulateSerpViewingTime(arg0 *model.SerpViewingLogParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CumulateSerpViewingTime", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CumulateSerpViewingTime indicates an expected call of CumulateSerpViewingTime.
func (mr *MockLogRepositoryMockRecorder) CumulateSerpViewingTime(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CumulateSerpViewingTime", reflect.TypeOf((*MockLogRepository)(nil).CumulateSerpViewingTime), arg0)
}

// StoreSearchSeeion mocks base method.
func (m *MockLogRepository) StoreSearchSeeion(arg0 *model.SearchSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreSearchSeeion", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreSearchSeeion indicates an expected call of StoreSearchSeeion.
func (mr *MockLogRepositoryMockRecorder) StoreSearchSeeion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreSearchSeeion", reflect.TypeOf((*MockLogRepository)(nil).StoreSearchSeeion), arg0)
}

// StoreSerpEventLog mocks base method.
func (m *MockLogRepository) StoreSerpEventLog(arg0 *model.SearchPageEventLogParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreSerpEventLog", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreSerpEventLog indicates an expected call of StoreSerpEventLog.
func (mr *MockLogRepositoryMockRecorder) StoreSerpEventLog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreSerpEventLog", reflect.TypeOf((*MockLogRepository)(nil).StoreSerpEventLog), arg0)
}

// StoreTaskTimeLog mocks base method.
func (m *MockLogRepository) StoreTaskTimeLog(arg0 *model.SerpViewingLogParamWithTime) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTaskTimeLog", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreTaskTimeLog indicates an expected call of StoreTaskTimeLog.
func (mr *MockLogRepositoryMockRecorder) StoreTaskTimeLog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTaskTimeLog", reflect.TypeOf((*MockLogRepository)(nil).StoreTaskTimeLog), arg0)
}
