version: '3'

services:
  elasticsearch:
    build: es
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9222:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    links:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      ELASTIC_SEARCH_URL: http://localhost:9222
      ELASTIC_SEARCH_HOSTS: http://localhost:9222

volumes:
  es-data:
    driver: local
